### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by jzp820927** [patrickbrandao/tcp-ping#1]
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

---

$ make
gcc  -g -Wall -O    -c -o tcp-ping.o tcp-ping.c
tcp-ping.c: In function ‘sigalarm’:
tcp-ping.c:79:11: warning: variable ‘now’ set but not used [-Wunused-but-set-variable]
  long int now;
           ^
tcp-ping.c: In function ‘do_tcp_connect’:
tcp-ping.c:141:3: error: ‘ipv6addr’ has an incomplete type
   server6.sin6_addr = ipv6addr; // _((struct in6_addr_)host->h_addr);
   ^
tcp-ping.c:154:3: error: ‘ipv4addr’ has an incomplete type
   server4.sin_addr = ipv4addr; // _((struct in_addr_)host->h_addr);
   ^
tcp-ping.c: In function ‘main’:
tcp-ping.c:311:3: warning: passing argument 1 of ‘inet_pton’ makes integer from pointer without a cast [enabled by default]
   ipv4addr = inet_pton(tmpstr);
   ^
In file included from tcp-ping.c:10:0:
/usr/include/arpa/inet.h:58:12: note: expected ‘int’ but argument is of type ‘char _’
 extern int inet_pton (int __af, const char *__restrict __cp,
            ^
tcp-ping.c:311:3: error: too few arguments to function ‘inet_pton’
   ipv4addr = inet_pton(tmpstr);
   ^
In file included from tcp-ping.c:10:0:
/usr/include/arpa/inet.h:58:12: note: declared here
 extern int inet_pton (int __af, const char *__restrict __cp,
            ^
tcp-ping.c:311:3: error: ‘ipv4addr’ has an incomplete type
   ipv4addr = inet_pton(tmpstr);
   ^
tcp-ping.c:326:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *_\* [tcp-ping.o] Error 1

**Comment by patrickbrandao** [comment]
Thank you, my friend!!
